# Generated by Django 4.0.4 on 2022-05-18 06:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employer', '0003_rename_locaation_jobss_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jobss',
            new_name='Jobs',
        ),
    ]
