# Generated by Django 4.0.4 on 2022-06-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0007_alter_applications_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employerprofile',
            old_name='bio',
            new_name='company_website',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='location',
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='about_us',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='address',
            field=models.TextField(default='', max_length=260),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='services',
            field=models.CharField(choices=[('Advertising', 'Advertising'), ('ELectronics', 'ELectronics'), ('Financial Sevices', 'Financial Sevices'), ('Market Reserarch', 'Market Reserarch'), ('Govt.Sectors', 'Govt.Sectors'), ('IT And Solutions', 'IT And Solutions'), ('Media & Entertainment', 'Media & Entertainment'), ('Telecom Service', 'Telecom Service'), ('Others', 'Others')], default='Advertising', max_length=130),
        ),
    ]
