# Generated by Django 4.0.4 on 2022-06-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0008_rename_bio_employerprofile_company_website_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='role',
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='company_website',
            field=models.URLField(max_length=120),
        ),
    ]
