# Generated by Django 4.0.4 on 2022-06-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0009_remove_jobs_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='last_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='qualification',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
