# Generated by Django 4.0.4 on 2022-05-19 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidateprofile',
            old_name='skils',
            new_name='skills',
        ),
    ]
